// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_synergy_master = "CgkIoIG63tweEAIQAQ"; // <GPGSID>
        public const string achievement_gold_player = "CgkIoIG63tweEAIQBw"; // <GPGSID>
        public const string achievement_master_of_sincerity = "CgkIoIG63tweEAIQCQ"; // <GPGSID>
        public const string achievement_customer_focus_master = "CgkIoIG63tweEAIQAw"; // <GPGSID>
        public const string leaderboard_high_score = "CgkIoIG63tweEAIQCw"; // <GPGSID>
        public const string achievement_platinum_player = "CgkIoIG63tweEAIQCA"; // <GPGSID>
        public const string achievement_agility_master = "CgkIoIG63tweEAIQBA"; // <GPGSID>
        public const string achievement_silver_player = "CgkIoIG63tweEAIQBg"; // <GPGSID>
        public const string achievement_safety_master = "CgkIoIG63tweEAIQBQ"; // <GPGSID>
        public const string achievement_god_of_sincerity = "CgkIoIG63tweEAIQCg"; // <GPGSID>
        public const string achievement_integrity_master = "CgkIoIG63tweEAIQAg"; // <GPGSID>

}

